"""Render the managed-section content (markdown) from related items + DeepWiki.

Structure follows the Codex review: separate "possibly related history" from
"current repo facts" and "open risks", and never present stale references as
authoritative.
"""

from __future__ import annotations

from secretary.semantic.reranker import RelatedItem

_GH = "https://github.com"

_CATEGORY_LABEL = {
    "duplicate_candidate": "possible duplicate",
    "implementation_overlap": "overlapping work",
    "conceptual_context": "related context",
    "historical_reference": "prior history",
}


def _item_line(default_repo: str, it: RelatedItem) -> str:
    repo = it.repo or default_repo
    url = f"{_GH}/{repo}/issues/{it.number}"  # GitHub redirects issues/<n> to PRs too
    label = _CATEGORY_LABEL.get(it.category, it.category)
    # Show owner/name#N only for cross-repo items; same-repo stays the terse #N.
    ref = f"{repo}#{it.number}" if it.repo and it.repo != default_repo else f"#{it.number}"
    why = f" — {', '.join(it.signals)}" if it.signals else ""
    return f"- [{it.kind} {ref}]({url}) · _{label}_ ({it.state}, conf {it.confidence:.2f}): {it.title}{why}"


def render_content(
    repo: str,
    related: list[RelatedItem],
    contexts: dict[str, str],
    *,
    run_ref: str = "",
) -> str:
    out: list[str] = ["## 🤖 OpenCouncil Secretary — context", ""]

    strong = [r for r in related if r.category != "weak_match"]
    out.append("### Possibly related history")
    if strong:
        out += [_item_line(repo, it) for it in strong]
    else:
        out.append("_No strong matches found._")
    out.append("")
    out.append(
        "> These are candidate links from semantic + structural signals — verify "
        "before relying on them; referenced items may be closed, reverted, or unmerged."
    )
    out.append("")

    out.append("### Current repo facts (DeepWiki)")
    any_ctx = False
    for repo_name, text in contexts.items():
        short = repo_name.split("/")[-1]
        if text:
            any_ctx = True
            out += [f"<details><summary>{short}</summary>", "", text, "", "</details>", ""]
        else:
            out.append(f"<details><summary>{short}</summary>\n\n_context unavailable_\n\n</details>\n")
    if not any_ctx:
        out.append("_DeepWiki context unavailable for all repos._")
    out.append("")

    footer = "_Auto-generated by OpenCouncil Secretary; manual edits inside this block are overwritten."
    if run_ref:
        footer += f" {run_ref}."
    footer += "_"
    out.append(footer)
    return "\n".join(out)
